### PR TITLE
Fixed Issue with Typo on Upload

### PR DESCRIPTION
**Pull request by jddalessandro**
* Typo was causing error on file upload
* Logging statement was using double quotes instead of backticks to log the port

### CODE REVIEW

**Comment by jddalessandro** [comment]
@zcarey90 I found the issue. you should merge the pull request, pull to your machine, and run it

**Comment by zcarey90** [comment]
Screen Shot 2020-12-18 at 11 39 47 AM

that definitely help out a lot but now after I did the pull and ran it I get this error

**Comment by jddalessandro** [comment]
well the error is pretty clear there, as it looks like you're using a method that doesn't exist. I'd refer back to the tesseract docs and API guide

https://github.com/naptha/tesseract.js/blob/master/docs/api.md

I don't see any progress method, so you'll have to look into the docs to accomplish the logging correctly.

**Comment by zcarey90** [comment]
I am kind of at a road block. I read the the github documents and then from there ended up on stackoverflow. The person on there is having the same problem as well and some people had a few suggestions and I was wondering what you thought about them?  https://stackoverflow.com/questions/62569165/referenceerror-progress-is-not-defined-tesseract       I am just wondering if that is the solution and if so how much how that new code would we need. Would we need all of that code in async?

**Comment by zcarey90** [comment]
Screen Shot 2020-12-18 at 12 14 49 PM

this is the new error

**Pull request merged**
